# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 05:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'abierto'), ('2', 'congelado'), ('3', 'pagado')], default='', max_length=1, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total')),
                ('totalImpuesto', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total impuesto')),
                ('fechaCreacion', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de creaci\xf3n')),
                ('fechaActualizacion', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de actualizaci\xf3n')),
            ],
            options={
                'verbose_name': 'Carrito de compras',
                'verbose_name_plural': 'Carritos de compras',
            },
        ),
        migrations.CreateModel(
            name='categoriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=350, null=True, verbose_name='Descripci\xf3n')),
            ],
            options={
                'verbose_name': 'Categoria producto',
                'verbose_name_plural': 'Categorias de productos',
            },
        ),
        migrations.CreateModel(
            name='lineaCarrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Subtotal')),
                ('montoImpuesto', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Impuesto')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.carrito', verbose_name='Carrito')),
            ],
            options={
                'verbose_name': 'Detalle de carrito de compras',
                'verbose_name_plural': 'Detalles de carritos de compras',
            },
        ),
        migrations.CreateModel(
            name='lineaOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Subtotal')),
                ('montoImpuesto', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Impuesto')),
            ],
            options={
                'verbose_name': 'Detalle de orden de compra',
                'verbose_name_plural': 'Detalle de ordenes de compras',
            },
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='microempresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=250, verbose_name='Raz\xf3n Social')),
                ('ruc', models.CharField(max_length=15, verbose_name='RUC')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono')),
                ('direccion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Direcci\xf3n')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('fechaCreacion', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de creaci\xf3n')),
                ('fechaActualizacion', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de actualizaci\xf3n')),
            ],
            options={
                'verbose_name': 'Microempresa',
                'verbose_name_plural': 'Microempresas',
            },
        ),
        migrations.CreateModel(
            name='orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'en espera'), ('2', 'confirmado'), ('3', 'entregado')], default='', max_length=1, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total')),
                ('totalImpuesto', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total impuesto')),
                ('fechaCreacion', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de creaci\xf3n')),
                ('fechaActualizacion', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de actualizaci\xf3n')),
                ('microempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.microempresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Ordenes de compras',
            },
        ),
        migrations.CreateModel(
            name='personaNatural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, verbose_name='DNI')),
                ('fechaCreacion', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de creaci\xf3n')),
                ('fechaActualizacion', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de actualizaci\xf3n')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, verbose_name='slug')),
                ('descripcion', models.TextField(blank=True, max_length=350, null=True, verbose_name='Descripci\xf3n')),
                ('rating', models.IntegerField(default=0, verbose_name='Ventas')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('precioUnitario', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio')),
                ('fechaCreacion', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de creaci\xf3n')),
                ('fechaActualizacion', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de actualizaci\xf3n')),
                ('seguimiento', models.BooleanField(default=False, verbose_name='Seguimiento')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.marca', verbose_name='Marca')),
                ('microempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.microempresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=250, verbose_name='Raz\xf3n Social')),
                ('ruc', models.CharField(max_length=15, verbose_name='RUC')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono')),
                ('direccion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Direcci\xf3n')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('microempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.microempresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='proveedorProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.microempresa', verbose_name='Empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor asignado',
                'verbose_name_plural': 'Proveedores asignados',
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.personaNatural'),
        ),
        migrations.AddField(
            model_name='microempresa',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.personaNatural'),
        ),
        migrations.AddField(
            model_name='marca',
            name='microempresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.microempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='lineaorden',
            name='microempresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.microempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='lineaorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.orden', verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='lineaorden',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='lineacarrito',
            name='microempresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.microempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='lineacarrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='microempresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.microempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='microempresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.microempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.personaNatural'),
        ),
    ]
