# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.personaNatural'),
        ),
        migrations.AlterField(
            model_name='microempresa',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.personaNatural'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.personaNatural'),
        ),
    ]
