# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20171122_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.categoriaProducto', verbose_name='Categoria'),
        ),
    ]
